logging:
  level:
    fr.bred: DEBUG
parameters:
  name: World
datasources:
  batch:
    platform: h2
    driver-class-name: org.h2.Driver
    username: sa
    password:
    jdbc-url: jdbc:h2:mem:jdbc:h2:mem:batch;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
batch:
  chunk:
    size: 10
csv:
  input: E:\batch-totem\input\
  output: E:\batch-totem\output\
  
url:
  bspublishmsg: https://bs-publishmsg-v2.ms.developpement.local/api
  bsauthentmanag: https://bs-authentmanag-v2.ms.developpement.local/api
  
servicecontext:
  batchUser:
    applicationId: batch-totem
    consumingId: TIWL
    consumingChannel: BATCH
    peo: 8347
    userId: svc_fti
    societyCode: "01"
    tokenContext: dummy