logging:
  level:
    fr.bred: DEBUG
parameters:
  name: World
datasources:
  batch:
    platform: h2
    driver-class-name: org.h2.Driver
    username: sa
    password:
    jdbc-url: jdbc:h2:mem:jdbc:h2:mem:batch;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
batch:
  chunk:
    size: 10
csv:
  output: E:\output\
  