logging:
  level:
    fr.bred: DEBUG
batch:
  chunk:
    size: 10
csv:
  input: E:\batch-totem\input\
  output: E:\batch-totem\output\
  
url:
  bspublishmsg: https://bs-publishmsg-v2.ms.developpement.local/api
  bsauthentmanag: https://bs-authentmanag-v2.ms.developpement.local/api
  
emailcontext:
  validationFailed:
      from: automail@bred-it.com
      to: wittakarn.keeratichayakorn@bred-it.com
      cc: wittakarn.expert@gmail.com
  
servicecontext:
  batchUser:
    applicationId: batch-totem
    consumingId: TIWL
    consumingChannel: BATCH
    peo: 8347
    userId: svc_fti
    societyCode: "01"
    tokenContext: dummy